### ISSUE TITLE
Create .gitignore file

### ISSUE THREAD

**Issue by ghost** [ep6-TH-Bingen/project_alpha_omega#11]
Create a .gitignore file.
It should prevent adding files/folders that are specific to IntelliJ and Maven.
A source could be [gitignore.io](https://www.gitignore.io/)

**Comment by nipafx** [comment]
Die Beschreibung ist etwas knapp. Sie sollte _mindestens_ die Informationen enthalten, die ich im OLAT hinterlassen habe.
