### ISSUE TITLE
Sprache für Kommentare festlegen

### ISSUE THREAD

**Issue by nipafx** [ep6-TH-Bingen/project_alpha_omega#13]
Eure README sagt:

> * for commenting the code you can use English or German

Bitte legt euch auf eins von beiden fest.

**Comment by EdenTewelde** [comment]
We agreed to communicate in English.

**Comment by nipafx** [comment]
Ok, I saw you changed it for GitHub communication as well. Was that on purpose.

:bulb: With pull requests we can discuss this _before_ the change is makes it into the repository.

**Comment by EdenTewelde** [comment]
Yes that was on purpose. Ok, thanks for the tip.

**Comment by nipafx** [comment]
👍
