### ISSUE TITLE
Release v1.0

### ISSUE THREAD

**Issue by EdenTewelde** [ep6-TH-Bingen/project_alpha_omega#15]
- Create a [git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging)
   in Git, type: "git tag -a v1.0 -m "tagging message" and push it
- make a [release](https://help.github.com/articles/creating-releases/) on GitHub
- build a jar with maven and upload it to the release

**Comment by nipafx** [comment]
Some details on how exactly to make a release once all issues in [the first milestone](https://github.com/ep6-TH-Bingen/project_alpha_omega/milestone/4) are done (pardom my German):

* `master` auschecken
* mit `mvn clean install` und `java-jar target/...jar` sicherstellen, dass alles funktioniert
* in der `pom.xml` bei der Version `-SNAPSHOT` entfernen
* nochmal `mvn clean install` und die JAR aus dem `target`-Ordner (beachte, dass `-SNAPSHOT` fehlt) irgendwohin kopieren
* neuen Commit auf `master` mit der Message "Release version 1.0" (oder so)
* den Commit taggen
* in der `pom.xml` die Version `2.0-SNAPSHOT` eintragen
* neuen Commit auf `master` mit der Message "Start work on 2.0" (oder so)
* alles pushen (mit tags)
* auf GitHub das Releases-Menü finden, aus dem Tag ein Release machen und die JAR anhängen

Den letzten Schritt hab ich schon lange nicht mehr gemacht, kann sein, dass ihr da ein wenig suchen müsst.

**Comment by nipafx** [comment]
This would be a good opportunity for those that did not contribute that much yet...
