### ISSUE TITLE
Increase permissions

### ISSUE THREAD

**Issue by nipafx** [ep6-TH-Bingen/project_alpha_omega#17]
I am only a _member_ of your organization ep6-TH-Bingen (you are _owners_), which keeps me from doing certain things. Can you change that? :smiley:

**Comment by nipafx** [comment]
For example, I can't add this issue to a milestone.

**Comment by ghost** [comment]
Sorry, overlooked that at the beginning. I think Eden changed it meanwhile.

**Comment by nipafx** [comment]
Yes, changed. Thx.
