### ISSUE TITLE
Create a simulation consisting of cars and an abstract, monolithic road network

### ISSUE THREAD

**Issue by Domm2501** [ep6-TH-Bingen/project_alpha_omega#19]
Should maybe have:
* Car Class with maybe the following:

    method that announces whether it wants to drive or not
    method that keeps track of whether they can drive or were delayed due to capacity exceeding
    // maybe more? A specific name like 1,2,3 to distinguish them or so

* Network Class with maybe the following:

    given/variable capacity
    method that tallies up the numbers of cars
    method that compares capacity with number of cars and decide like this:
    resultOf{Method that tallies up the numbers of cars} <= capacity -> cars drive
    resultOf{Method that tallies up the numbers of cars} > capacity -> cars are delayed
    // maybe more?
Edited at 03.08.2017 at 16:15

**Comment by EdenTewelde** [comment]
I would add a method that creates a new car taking the information whether it wants to drive. If it wants to drive it should be added to a mutableList, so we can keep track of how many cars there are on the road network.

**Comment by Domm2501** [comment]
The thing that strikes me here is: What comes first? The CSV file containing the information whether the car actually wants to drive or not, OR the method where the car itself announces whether it actually wants to drive or not which is then given into the CSV file as "input". Or does the method just read the CSV file and say: "In the CSV file it says I want to drive, so I want to drive!"
But yeah, your way seems good, Eden.

**Comment by SoerenDbl** [comment]
I also prefer Edens way, so we can just create and use a method itself. I'll work on it tomorrow so we can discuss about the final solution afterwards.

**Comment by nipafx** [comment]
This issue may be a little "small". It is very tough to design a class on its own without working on the ones it cooperates with. I asked you to "create one issue per top-level bullet" and the top-level bullet for this task looked as follows:

> * create a simulation consisting of cars and an abstract, monolithic road network (meaning it does not yet consist of individual roads - it’s just a single network); each car knows whether it wants to drive and the road network has a total capacity for cars; implement a single simulation step (which is supposed to represent one hour), where:
>
>    * each individual car announces whether it wants to drive or not
>    * the network tallies up the number of cars on the road and compares it to its own capacity
>    * the network decides for each car whether it drives or is delayed due to traffic jams; that decision is based on how many cars are on the road compared to the network’s capacity:
>        * less than or equal to capacity ~> all can drive
>        * over capacity ~> all are delayed

This was the smallest self-contained task I could come up with that gets the simulation going. I doubt there is a sensible way to cut it into smaller tasks. This task and the discussion also conflates coding the car with creating it from CSV and tracking whether it was allowed to drive or not. There is no need to do all of that at once.

Don't let me keep you, though. :smiley: You can do it this way if you think that works better.

**Comment by SoerenDbl** [comment]
Maybe we should make changes to the issues first to clear things up a little.

**Comment by nipafx** [comment]
Yes, that might be a good idea. Note that you're not quite done with [Milestone 1](https://github.com/ep6-TH-Bingen/project_alpha_omega/milestone/4), though, so maybe focus on that first.

**Comment by Domm2501** [comment]
I am well aware that those things should be done simultaneously, I just wanted to open all issues to stir a discussion and to show everyone (including myself) how much actually has to be done.

**Comment by EdenTewelde** [comment]
I would also prefer to change the issues so we have one per top-level bullet.

**Comment by EdenTewelde** [comment]
A general question about the task: do the cars decide whether they want to drive and **then** the road network "tells" them if they're able to drive or are delayed? Or is it like: a car only wants to drive when there's no traffic jam?

**Comment by nipafx** [comment]
No, the car has a need to drive (well, the driver has, but you get my point) and tries to do so regardless of traffic. It succeeds or fails based on how many other cars (drivers) had the same idea.
