### ISSUE TITLE
Create Main Program

### ISSUE THREAD

**Issue by Domm2501** [ep6-TH-Bingen/project_alpha_omega#21]
Should have:
* uniVocity parser to parse input (cars & their interest  to drive)
// So there should be a CSV-file as input that consists of cars & their interest to drive, and the main program should be able to convert the given information in that file to use it in the simulation
* Resulting data (drive VS delay) as CSV-file
* scenario function which is a different issue
// maybe more?

**Comment by nipafx** [comment]
Currently the `Car` class needs two things to be created: whether it wants to drive and a network. The first information can come from CSV, the second not (just create an instance). To identify cars, it helps giving them an od, so the `Car` constructor could look like this:

    class Car(val id: Int, val wantsToDrive: Boolean, val roadNetwork : Network, var delayed : Boolean? = null)

The CSV could then look as follows:

    Car, Drive
    1, true
    2, false
    3, false
    4, true

For the output, you should then write the id and whether the car was delayed (which is also an attribute it has). It could look like this:

    Car, Drive
    1, false
    4, true
