### ISSUE TITLE
Create Scenario Method

### ISSUE THREAD

**Issue by Domm2501** [ep6-TH-Bingen/project_alpha_omega#23]
* A single simulation step is supposed to represent one hour
* Per simulation step each car announces whether it wants to drive or not.
// The question here is: Are cars able to change their desire to drive at all? If so, how often, etc.
* They are then getting tallied up and compared to the network's capacity. 
* Let the cars keep track of whether they can drive or were delayed and print that information at the end of the simulation
// maybe more?

**Comment by nipafx** [comment]
I think it helps to discuss what still needs to be done. On the current `master`, the `analyzeNetwork` already does quite a lot of what is needed:

* it represented a analysis step
* it adds up the required capacity
* it decides whether the network is over capacity
* it correctly informs cars what happened

What do you think needs to happen to resolve this issue?

**Comment by EdenTewelde** [comment]
The car needs to announce whether it wants to drive or not. Is anything else missing?

**Comment by nipafx** [comment]
> The car needs to announce whether it wants to drive or not.

As it stands, it does that in its own `init` block, when it adds itself to the network's `listOfCarsDriving` list. I think a better design would be if a third class (neither `Car`, nor `Network`) would create a list of cars and then give that to the network. That could then call a method on each car, finding out whether it wants to drive.

> Is anything else missing?

For the simple scenario, someone needs to create that list of cars, pass it to the network and then later look at what happened to the cars.

**Comment by EdenTewelde** [comment]
I don't quite understand the benefit of a third class (e.g. List) that takes care of the listOfCars. Is it "only" for design reasons?

**Comment by nipafx** [comment]
I'm proposing a third class _that produces the list_ - we can't use `List` itself for that because we can't edit that class.

There are reasons not to have the `Car` add itself to the list in the `Network`, particularly not to the second list of cars that want to drive. It's not easy to succinctly explain them, though, so I won't try. (Isn't that a great excuse?!) The code you wrote works and that's fine for now. :smiley: If future requirements are hard to implement due to the current design you will notice or I will point it out.

With that said, you still need some code that actually creates a bunch of cars and later checks whether they were delayed or not. Where do you propose to put that code?

**Comment by EdenTewelde** [comment]
Okay, I understand and will make the changes and add a new class. (before with "List" I meant it only as a name for the third class, not the List, misunderstanding 😃) 

I would create a function "scenario" that creates a given number of cars und checks if they were delayed. Can I do it like this or is there a better way?

**Comment by EdenTewelde** [comment]
Another question about the third class: my idea is now to create a function "addCar", that adds the new Car object to the list. Can I then call this function in the init block of the class Car?

**Comment by nipafx** [comment]
> I would create a function "scenario"

In which file does that go? I think neither the `Car` nor the `Network` should be tasked with setting up the simulation.

> Can I then call this function in the init block of the class Car?

Yes, but depending on where you put the method, I might complain of that later. :wink: Just give it a go and open a PR.

**Comment by EdenTewelde** [comment]
Can the scenario method go in the main file?

**Comment by SoerenDbl** [comment]
![img_0491](https://user-images.githubusercontent.com/30464368/29086700-bbd58b96-7c73-11e7-903e-8a583e8bbb54.PNG)
Doesn't the task say that the scenario shouldn't be connected (or attached) to the main program? Or does that only count for .csv-file?

**Comment by EdenTewelde** [comment]
I saw that but the scenario function is not within the main program, so I thought it should be fine. Also I didn't know where else to put it 😃

**Comment by nipafx** [comment]
The function can go into the same file and you can call it from `main` to try it out. (It's meant as a fallback during times where CSV does not work properly.)

**Comment by Domm2501** [comment]
So just to clarify things: It should be like this, right?
input.csv file -> this is the input for the CARS
network capacity -> This is the one thing you should be able to change DIRECTLY, if you want to change something about the cars, you need to do that in the .csv file
And the scenario function should just "compare" the cars (the cars that actually WANT to drive) with the capacity and delay them if need be. 
Afterwards, the outcome should be written into another .csv file (whether the cars had to be delayed due to the network).
But as of right now I just don't see any of that really being the case in the code.

**Comment by nipafx** [comment]
Not like that, no.

There should be code that, given a list of cars and network capacity, can simulate traffic. This currently happens in `Network`. But where do cars and capacity come from? Here's where CSV and `scenario` come in:

* the CSV code loads the cars from CSV files, calls `Network` to run the simulation, and writes the result to CSV
* the `scenario` function creates a hard-coded list of cars, calls `Network` to run the simulation, and writes the result with `prinltn`

So there are always two ways to execute a simulation: via CSV or directly from code. The reason for having two is that CSV parsing might sometimes break between pull reuquests and I wanted to make sure that you always have a way to run the simulation.

**Comment by Domm2501** [comment]
I don't know, I'm pretty sure that I did exactly the same thing in my pull request (cars being created randomly and also input through .csv) and it was deemed "not good".

**Comment by nipafx** [comment]
If you can point me to the specific PR, where I said it was not good, I might be able to explain it better.
