### ISSUE TITLE
Randomize the decision for whether each individual car can drive or gets delayed

### ISSUE THREAD

**Issue by Domm2501** [ep6-TH-Bingen/project_alpha_omega#26]
less than at 50% capacity: 5% chance of delay
less than at 70% capacity: 10% chance of delay
less than at 90% capacity: 20% chance of delay
less than at 110% capacity: 30% chance of delay
less than at 125% capacity: 50% chance of delay
less than at 150% capacity: 70% chance of delay
above 150% capacity: 90% chance of delay
//My mathematical translation for this would be the following:
x represents total amount of cars in percentage
y represents chance of delay in percentage
x > 150 -> y = 90
125 <= x <= 150 -> y = 70
110 <= x < 125 -> y = 50
90 <= x < 110 -> y = 30
70 <= x < 90 -> y = 20
50 <= x < 70 -> y = 10
x < 50 -> y= 5

// So here the normal simulation doesn't work anymore since when the capacity exceeds 100% all cars are delayed. Yet here it is randomly decided if cars that actually want to drive get delayed based on the capacity at hand.
//
What has to be done here:
* cars still need to be tallied up and compared to the capacity of the network
* now the chance of delay is applied to all the cars that want to drive (not to the cars that do not want to, although it wouldn't matter seeing that their value is zero anyway)
* If the chance of delay has been applied there needs to be another comparison between the cars and the network
* if number of cars > capacity -> all cars are delayed (this can still happen, although unlikely)

//maybe more? Or maybe I didn't really understand the task?

**Comment by Domm2501** [comment]
This is already done and is (hopefully) working as intended. Just waiting for the release of v2.0
Again, testing seems pretty weird because of the random numbers being generated.

**Comment by nipafx** [comment]
Working ahead is risky. People might change code in the files you changed, which is not easy to fix without some technical chops.

**Comment by Domm2501** [comment]
Seeing as I don't really know how you guys want to do it, you can take a look at this.

```kotlin
fun main(args: Array<String>) {
    val roadNetwork = readNetworkFromCsv("/cars.csv")
    var ListOfInterest:MutableList<Boolean> = mutableListOf()
    for (car in roadNetwork.listOfCars) {
        ListOfInterest.add(car.wantsToDrive)
    }
        roadNetwork.analyzeNetwork()
        val capacity = roadNetwork.capacity
        val numberOfCarsThatWantToDrive = roadNetwork.listOfCarsDriving.size.toDouble()
        val x = numberOfCarsThatWantToDrive / capacity
        val y = switchCase(x)
        val yProzent = y*100
        val z = revertBackToBoolean(applyingDelay(ListOfInterestInteger(ListOfInterest),y))
        println("List of cars after the chance of delay ($yProzent percent) has been applied: $z")
        writeNetworkToCsv(roadNetwork, "ResultingData.csv")
    }

private fun readNetworkFromCsv(fileName: String): Network {
    //Changed the return "Car" into "Network", because there is the "listOfCars"
    val capacity = 20
    val settings = CsvParserSettings()
    settings.format.setLineSeparator("\n")
    settings.isHeaderExtractionEnabled = true
    val csvParser = CsvParser(settings)
    val reader = FileAccess().getReader(fileName)
    val carRows: MutableList<Record> = csvParser.parseAllRecords(reader)

    val listOfCars: MutableList<Car> = mutableListOf()
    for (car in carRows) {
        val carID = car.values.get(0)
        val id = carID.toInt()

        val carStatus = car.values.get(1)
        val status = carStatus.toBoolean()

        val newCar = Car(id, status)
        listOfCars.add(newCar)
    }

    return Network(capacity, listOfCars)
}

private fun writeNetworkToCsv(network: Network, fileName: String) {
    val settings = CsvWriterSettings()
    settings.format.setLineSeparator("\n")

    val writer = FileAccess().getWriter(fileName)
    val csvWriter = CsvWriter(writer, settings)
    csvWriter.writeHeaders("Car-ID", "status", "delayed")

    val carRows: MutableList<Array<Any>> = mutableListOf()
    for (car in network.listOfCars) {
        val id = car.id
        val status = car.wantsToDrive
        val delayed = car.isDelayed
        val row: Array<Any> = arrayOf(id, status, delayed)
        carRows.add(row)
    }

    csvWriter.writeRowsAndClose(carRows)
}

fun scenario(numberOfCars: Int, capacity: Int) {
    /*
    * Creates a given a number of cars, every other car wants to drive
    * A road network is created with the given capacity
    * The road network is analyzed and it is printed whether a car is delayed or not
    */
    val listOfCars: MutableList<Car> = mutableListOf()
    for (i in 1..numberOfCars) {
        val newCar = Car(i, i % 2 == 0)
        listOfCars.add(newCar)
    }

    val road = Network(capacity, listOfCars)
    road.analyzeNetwork()
    for (car in road.listOfCars) {
        println("Does car #" + car.id + " want to drive? " + car.wantsToDrive)
        if (car.wantsToDrive == true) {
            println("Is car #" + car.id + " delayed? " + car.isDelayed)
        }
    }
}
fun ListOfInterestInteger(ListOfInterest:MutableList<Boolean>):MutableList<Int>{
    var ListOfCarInterestToDriveInteger:MutableList<Int> = mutableListOf()
    var carInterestToDrive : Int = 0
    for (car in ListOfInterest){
        if (car==true){
            carInterestToDrive = 1
        }
        if (car==false){
            carInterestToDrive = 0
        }
        ListOfCarInterestToDriveInteger.add(carInterestToDrive)
    }
    return ListOfCarInterestToDriveInteger
}

fun switchCase(x:Double):Double {
    var y :Double = 0.0
    if (x > 1.5) {
        y = 0.9
    }
    if ((1.25 <= x) && (x <= 1.5)) {
        y = 0.7
    }
    if ((1.1 <= x) && (x <= 1.25)) {
        y = 0.5
    }
    if ((0.9 <= x) && (x <= 1.1)) {
        y = 0.3
    }
    if ((0.7 <= x) && (x <= 0.9)) {
        y = 0.2
    }
    if ((0.5 <= x) && (x <= 0.7)) {
        y = 0.1
    }
    if (x < 0.5) {
        y = 0.05
    }
    return y
}

fun applyingDelay(ListOfCarsInterestToDriveInteger:MutableList<Int>,y:Double):MutableList<Int>{
    var ListOfCarsAfterDelay:MutableList<Int> = mutableListOf()
    for (car in ListOfCarsInterestToDriveInteger){
        if (car==1) {
            val z = Math.random()
            var value = 1
            if (y > z) {
                value = 0
            }
            ListOfCarsAfterDelay.add(ListOfCarsInterestToDriveInteger.get(car) * value)
        }
        if (car==0){
            ListOfCarsAfterDelay.add(ListOfCarsInterestToDriveInteger.get(car) * 0)
        }
    }
    return ListOfCarsAfterDelay
}

fun revertBackToBoolean(ListOfCarsAfterDelay:MutableList<Int>):MutableList<Boolean>{
    var ListOfCarsAfterDelayBoolean: MutableList<Boolean> = mutableListOf()
    var trueOrFalse:Boolean = true
    for (car in ListOfCarsAfterDelay){
        if (car==1){
            trueOrFalse = true
        }
        if (car==0){
            trueOrFalse = false
        }
        ListOfCarsAfterDelayBoolean.add(trueOrFalse)
    }
    return ListOfCarsAfterDelayBoolean
}
```

**Comment by Domm2501** [comment]
What this does is basically the following:
* Takes interestToDrive from .csv file and converts it into integer from boolean
* Applies the delay by comparing the generated random number ( Math.random() ) to numberOfCarsThatWantToDrive / capacityOfNetwork and the resulting chance of delay
* converts the delay back to boolean

**Comment by EdenTewelde** [comment]
You can get the number of cars that want to drive also like this (after running roadNetwork.analyze):
`val numberOfCarsThatWantToDrive = roadNetwork.listOfCarsDriving.size`
since analyzeNetwork goes over the list of all cars and adds only the cars that want to drive to the listOfCarsDriving

**Comment by Domm2501** [comment]
I still need the ListOfInterestToDrive though, because that is what we multiply with the value that we assign after we compare Math.random() to the chance of delay.
Obviously this would need to go into the scenario function and not the main function.
Edit: I implemented your thought into the code above.

**Comment by nipafx** [comment]
I'm assuming that all of this is supposed to go into the `Main` file. If it's not, all of what I say can be ignored.

This approach is doing a lot of the right things but on the wrong level of abstraction. What I mean by that is that it seems to be concerned a lot with loading cars from CSV and, like the other PR I commented on, pushing around ones and zeros. Object-oriented programming allows a much less technical solution.

@Domm2501, leave your code aside for the moment (you will use parts of it later) and think about it this way: You are supposed to randomize the decision whether an individual car is getting delayed or not. While the _randomization_ part is new, the _decision_ part is not. There is already code that makes that exact decision and, given the capacity limit and the capacity requirements, lets cars drive or get delayed.

Look for that code and and then think how it would need to change to make that decision random.

**Comment by Domm2501** [comment]
But this is the part I don't understand: "What I mean by that is that it seems to be concerned a lot with loading cars from CSV..."
YES! Why else would the .csv file be there for? I mean why shouldn't I be concerned with what is considered the INPUT?

**Comment by Domm2501** [comment]
And I just put all of that in the main function because I wanted to execute it to see whether it did the right thing.

**Comment by nipafx** [comment]
Writing a program is a big task. It is only solvable (especially in a team) by cutting it into smaller pieces (issues) and looking at each piece separately. The "read from CSV" piece is [already there](https://github.com/ep6-TH-Bingen/project_alpha_omega/blob/master/src/main/kotlin/Main.kt#L13-L36) - why do it again? Instead focus on the piece that you need to contribute.

> I mean why shouldn't I be concerned with what is considered the INPUT?

Yes, but you have to pick the right input. To randomize delays, you need two inputs: capacity limit and required capacity. So you should ask yourself where in the program these information exist? Not entirely coincidentally, this will lead you to the exact place in the code, where your piece fits in.

**Comment by Domm2501** [comment]
Because I need the second row of the .csv, that's why I originally planned to seperate both rows. Now it's one combined row from the type record and since I don't know how to extract that information and convert it into the right data type, I did it like that.

**Comment by EdenTewelde** [comment]
when readNetworkFromCsv is called, it gives back a roadNetwork. So in there we have a list of cars and in each object Car you have the information whether it wants to drive or not. Is this the information you needed?

**Comment by nipafx** [comment]
At least one of us is really missing something here. Maybe it's me. What information exactly are you trying to get from the CSV file that are not present in the `Car` instances.

(If it's not me, please make a best effort to follow [the advise I gave](https://github.com/ep6-TH-Bingen/project_alpha_omega/issues/26#issuecomment-321266727), [twice](https://github.com/ep6-TH-Bingen/project_alpha_omega/issues/26#issuecomment-321271938).)
