### ISSUE TITLE
Cover an entire day by simulating 24 steps in a row

### ISSUE THREAD

**Issue by Domm2501** [ep6-TH-Bingen/project_alpha_omega#27]
* cars now need to know for each of the 24 hours whether they want to drive or not
// This could be implemented by randomizing a number between 0 and 1 (1=want to drive; 0=doesn't want to drive)
 If generated number >= 0.5 -> use a function that rounds up to 1
If generated number < 0.5 -> use a function that rounds down to 0
Or should this not be random?
//
* if a car gets delayed it can not “fulfill” it’s desire to drive, meaning it has to try to drive again in the next step 
* extend result tracking by making sure that each car knows for every step whether it could drive or was delayed
* update the scenario function to the simulation’s new requirements

**Comment by EdenTewelde** [comment]
I agree with your first bullet point, but there might be an easier way: 
`Random().nextBoolean`

**Comment by nipafx** [comment]
The current desire to drive is defined during construction, either because of a fixed value in `scenario` or because of what was read from CSV. Likewise the hourly desire should also be defined during construction. (The `scenario` function should be updated as part of this issue, CSV parsing as part of #28.)

**Comment by EdenTewelde** [comment]
But the definition during construction can be random?

**Comment by nipafx** [comment]
Yes, `scenario` could make that decision at random if it wants to. (I now realize that that could have been @Domm2501's and your intention all along, in which case I just didn't get it.)

**Comment by EdenTewelde** [comment]
I'm not sure what scenario should print now. Suggestions anyone?
