### ISSUE TITLE
Extend CSV input/output to match the new requirements and results

### ISSUE THREAD

**Issue by Domm2501** [ep6-TH-Bingen/project_alpha_omega#28]
* Extend input to include for each hour whether a car wants to drive
* Extend output to include for each hour whether the car drove or was delayed

**Comment by EdenTewelde** [comment]
Do we want to extend the input by using a function that adds a new column to add whether a car wants to drive or not or should we do it by hand?
Also what do you think how the input csv-file should look like? 
My first ideas were:
* id, hour, wantsToDrive
 1, 1, true
1, 2, true
1, 3, false
1, 4, true ...
* id, hour, wantsToDrive
1, 1, true
2, 1, false
3, 1, true ...

Of course we could change the order of "hour" and "wantsToDrive"

**Comment by nipafx** [comment]
@EdenTewelde You make it sound as if `isDelayed` is an input.

**Comment by EdenTewelde** [comment]
Oh, that's right, I always confuse wantsToDrive with isDelayed. I'll edit the comment above

**Comment by ghost** [comment]
I have a question to the idea of Eden... if I  change the input csv "cars.csv" having 15 cars, and for each car 24 hours/steps, would this be the right way? I´m just asking, because I would like to take part on this issue, and want to know if this is is the right starting point for me.

**Comment by nipafx** [comment]
Eden's idea is interesting and worth pursuing (I originally had something else in mind but this doesn't seem to be worse). One thing, though: Having to put `true`/`false` in for 24 hours is kinf of redundant (and cumbersome). Why not...

    id,wantsToDriveAtHour
    1, 8
    1, 9
    1, 10

...with the assumption that car `1` does not want to drive from 1-7 and 11-23?

Another tip: This isse does _not_ include extending the simulation itself! Giving the car a list of hours it wants to drive on top of the current attributes and then have it ignore them until someone else uses it to implement #27 is advicable. The same for output (save at which hours car could drive or was delayed).

**Comment by EdenTewelde** [comment]
Does anyone has an idea about how the output should look like?

**Comment by ghost** [comment]
Maybe the cars that a delayed because of not enough road capacity, are marked with "delayed", the cars that are driving with nothing? Like the walls in airports?

**Comment by EdenTewelde** [comment]
And an extra column with the hour?
