### ISSUE TITLE
Issues erstellen

### ISSUE THREAD

**Issue by nipafx** [ep6-TH-Bingen/project_alpha_omega#3]
Bitte erstellt einen Meilenstein für die Projektinfrastruktur und Issues für jede Aufgabe. Denkt daran, dass ihr PRs erst mergen sollt, wenn ich :+1: gegeben habe.

**Comment by nipafx** [comment]
As far as I can tell you still need to create the Travis ticket but then you can close this one.

**Comment by EdenTewelde** [comment]
Alright.
