### ISSUE TITLE
README

### ISSUE THREAD

**Issue by ghost** [ep6-TH-Bingen/project_alpha_omega#8]
Create README.md, it should contain:

- description of the project
- team members
- language (English or German)
- document the license and the code of conduct
- tell users how to launch the application

**Comment by Domm2501** [comment]
Do we need confirmation from Mr.Parlog aswell to close issues we think are resolved?

**Comment by nipafx** [comment]
No. You can close an issue once I agreed to the corresponding PR. In this specific case, it looks like the last bullet still needs to be addressed.

**Comment by EdenTewelde** [comment]
I am not sure how a user would launch the application. Does anyone have an idea? 
My first thought was that the user would have to enter "java -jar project_alpha-1.0-SNAPSHOT-jar-with-dependencies.jar" at the prompt (or Windows PowerShell). What do you think about that?

**Comment by nipafx** [comment]
Yes, that's exactly what I was looking for. :wink: After the first release you can add a sentence or two, where to get that JAR from.

**Comment by ghost** [comment]
I updatet my local repo after the last PRs, and tried the .jar-build with maven and PowerShell.
After the command _mvn clean install_ the target directory was created with the expected files inside.
If I doubleclick the file _project_alpha-1.0-SNAPSHOT-jar-with-dependencies.jar_ nothing happens. And the command _java -jar project_alpha-1.0-SNAPSHOT-jar-with-dependencies.jar_ ends in
_ERROR: unable t acces jarfile project_alpha-1.0-SNAPSHOT-jar-with-dependencies.jar_
The _target_ -directory is in the project_alpha_omega directory with the dir. _src_ , and the files of the pom, Readme etc. 

Has anyone an idea what i´m doing wrong or what the problem could be?

**Comment by EdenTewelde** [comment]
Could you post a screenshot of this?

**Comment by ghost** [comment]
![jar_fail](https://user-images.githubusercontent.com/27009025/28921884-158d3dde-7858-11e7-831f-1623d000b771.JPG)

**Comment by EdenTewelde** [comment]
Sorry, I made a mistake with the name of the jar file. It has to be:
project_alpha_omega-1.0-SNAPSHOT-jar-with-dependencies.jar
Now, it should work.

**Comment by ghost** [comment]
![jar_check](https://user-images.githubusercontent.com/27009025/28922039-dbe2067c-7858-11e7-812f-4a1fd6c6883b.JPG)

Yes, worked. Thanks.

**Comment by EdenTewelde** [comment]
Okay 😃
